### ISSUE TITLE
Bug in Example Config Generation

### ISSUE THREAD

**Issue by skammerdiener** [mozilla/csp-logger#14]
I get the following error when trying to run the code with the example.json file.

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at loadConfigurationFile (S:\SRC\Miscellaneous\csp-logger-master\node_module
s\log4js\lib\log4js.js:299:17)
    at Object.configure (S:\SRC\Miscellaneous\csp-logger-master\node_modules\log
4js\lib\log4js.js:363:14)
    at module.exports (S:\SRC\Miscellaneous\csp-logger-master\lib\stores\logger.
js:7:10)
    at Object.init (S:\SRC\Miscellaneous\csp-logger-master\lib\store.js:10:41)
    at Object.<anonymous> (S:\SRC\Miscellaneous\csp-logger-master\csp-logger.js:
25:38)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

[example.zip](https://github.com/mozilla/csp-logger/files/1647041/example.zip)

**Comment by naugtur** [comment]
Hi, I'm busy with a newborn and unlikely to debug this right now. Would you mind finding out what's wrong and suggesting where the bug is or submitting a PR?
